name: CICD

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    name: Test (Node.js v${{ matrix.node_version }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental:
          - false
        node_version:
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - name: Install npm v6
        if: ${{ matrix.node_version >= 15 }}
        run: |
          npm install -g npm@6
      - name: Install Dependencies
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Tests
        run: |
          npm test
          npm run build:web
  publish:
    name: Publish (maybe)
    runs-on: ubuntu-latest
    needs: test
    if: |
      startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Install Dependencies
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build & Publish Packages
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



